#!/usr/bin/python3

import sys
import os
import re
import urllib.request

blocks_url = "https://www.unicode.org/Public/UNIDATA/Blocks.txt"
re_blocks_line = re.compile("([0-9a-fA-F]+)..([0-9a-fA-F]+); (.*)")

def escape_quotes(s):
    return s.replace("\\", "\\\\").replace("\"", "\\\"")

def parse_unicode_blocks_file(blocks_path):
    # Parse the Blocks.txt file
    # Non-comment lines are of the form:
    # <hexcode>..<hexcode>; <blockname>
    blocks = []
    line_no = 0
    with open(blocks_path, "r") as f:
        for line in f:
            line_no += 1
            line = line.strip()
            hash_pos = line.find('#')
            if hash_pos >= 0:
                line = line[:hash_pos]
            if not line:
                continue
            m = re_blocks_line.match(line)
            if not m:
                print("line %d:\n%s\ndoes not match <hexcode>..<hexcode>; <blockname>" % (line_no, line))
                sys.exit(1)
            range_start = int(m.group(1), 16)
            range_end = int(m.group(2), 16)
            block_name = m.group(3)
            blocks.append((range_start, range_end, block_name))
    return blocks

if len(sys.argv) < 2:
    print("Usage: ./genunicodedatajs.py <destdir>")
    sys.exit(1)

dest_dir = sys.argv[1]
unidata_dir = os.path.join(dest_dir, "unidata")
blocks_path = os.path.join(unidata_dir, "Blocks.txt")
unicodedatajs_path = os.path.join(dest_dir, "unicodedata.js")

if not os.path.exists(blocks_path):
    if not os.path.exists(unidata_dir):
        print("%s does not exist. Creating it." % (unidata_dir))
        os.mkdir(unidata_dir)
    print("%s does not exist. Fetching it from %s" % (blocks_path, blocks_url))
    urllib.request.urlretrieve("https://www.unicode.org/Public/UNIDATA/Blocks.txt", blocks_path)

blocks = parse_unicode_blocks_file(blocks_path)

# Write the information out to unicodedata.js
with open(unicodedatajs_path, "w") as f:
    print("""
/* There's no need to edit this file manually.

   It is automatically generated by genunicodedatajs.py from the Blocks.txt
   file which that script fetches from:
   https://www.unicode.org/Public/UNIDATA/Blocks.txt
*/

const unicodeBlocks = [""", file=f)

    blocks = sorted(blocks)
    for (range_start, range_end, block_name) in blocks:
        print("    [ 0x%04x, 0x%04x, \"%s\" ]," % (range_start, range_end, escape_quotes(block_name)), file=f)

    print("];", file=f)

    print("""

function getUnicodeCodepointBlock(cp) {
    /* Binary search in unicodeBlocks until we find the correct one */
    let l = 0;
    let r = unicodeBlocks.length - 1;

    while (l <= r) {
        let pos = Math.floor((l + r) / 2);
        let blk = unicodeBlocks[pos];
        if (cp < blk[0]) {
            r = pos - 1;
        }
        else if (cp > blk[1]) {
            l = pos + 1;
        }
        else {
            return blk[2];
        }
    }
    return "No block";
}
""", file=f)

print("Successfully wrote " + unicodedatajs_path)
